require 'yaml'
require 'socket'
require 'time'

module LuxDeploy
  # Snapshot of what is wired up on the host for one app after a successful
  # deploy. Written to <app_dir>/lux-deploy.yaml mode 0644. Safe to read by
  # humans, LLMs, monitoring scripts - never contains secrets.
  module Manifest
    module_function

    FILENAME ||= 'lux-deploy.yaml'

    # Keys whose values are stripped from the env section. Matched on the
    # uppercased key name, substring (so SECRET, JWT_SECRET, DB_MAIN, DB_URL,
    # DATABASE_URL, MY_API_TOKEN, AWS_ACCESS_KEY_ID all redact). As a backstop,
    # any value carrying URL-embedded credentials (user:pass@) is redacted
    # regardless of key name - see sensitive_value?.
    SENSITIVE_KEY_PATTERNS ||= %w[SECRET PASSWORD TOKEN KEY DB_MAIN DB_URL DATABASE_URL CREDENTIAL].freeze

    # Value carrying URL-embedded credentials, e.g. postgres://user:pass@host/db
    # or password-only forms like redis://:pass@host (empty username).
    CREDENTIAL_URL ||= %r{://[^/\s:@]*:[^/\s@]+@}

    # Returns the YAML body ready to upload (with a header comment).
    def render(ctx)
      header = <<~TXT
        # Generated by lux-deploy #{LuxDeploy::VERSION} on every successful deploy.
        # Snapshot of what is currently wired up on this host for this app.
        # Safe to read; do not edit (next deploy overwrites).
      TXT
      header + YAML.dump(stringify(build(ctx)))
    end

    def build(ctx)
      # Domains come from yaml `domain:` (the sole source of truth post
      # .env/.yaml split). env_snapshot is a redacted snapshot of the
      # rendered .env contents - informational only, never used for
      # template substitution.
      domains      = ctx.config.domain.to_s.split(',').map(&:strip).reject(&:empty?)
      env_snapshot = Template.parse_env(ctx.rendered['.env'])

      {
        deployed_at:  Time.now.utc.iso8601,
        app:          ctx.app,
        domain:       ctx.domain,
        domains:      domains,
        url:          "https://#{ctx.domain}",
        git:          git_info(ctx.branch),
        deploy: {
          triggered_by: triggered_by,
          host:         ctx.host,
          service_user: ctx.config.service_user,
          app_dir:      ctx.app_dir,
          port:         ctx.port,
          ports:        ctx.ports,
          ruby:         (ctx.ruby_used? ? ctx.ruby_path : nil)
        },
        paths: {
          release:     "#{ctx.app_dir}/release",
          old_release: "#{ctx.app_dir}/old-release",
          shared:      "#{ctx.app_dir}/shared",
          tmp:         "#{ctx.app_dir}/shared/tmp",
          log:         "#{ctx.app_dir}/shared/log",
          env_file:    "#{ctx.app_dir}/.env",
          manifest:    "#{ctx.app_dir}/#{FILENAME}"
        },
        services: services_section(ctx),
        caddy: {
          site_link: "#{CADDY_SITES}/#{ctx.app}.caddy",
          source:    "#{ctx.app_dir}/caddy.config",
          reload:    'systemctl reload caddy'
        },
        hooks:     hooks_section,
        env:       env_section(env_snapshot),
        artifacts: ctx.rendered.keys.sort,
        engine: {
          lux_deploy_version: LuxDeploy::VERSION,
          service_prefix:     ctx.config.service_prefix,
          remote_base:        ctx.config.remote_base
        }
      }
    end

    # One block per discovered service (web + every extra *.service), keyed
    # by service name. ExecStart is pulled from each rendered unit.
    def services_section(ctx)
      ctx.services.each_with_object({}) do |s, out|
        out[s.name] = {
          unit:         "#{s.unit}.service",
          systemd_link: "#{SYSTEMD_DIR}/#{s.unit}.service",
          source:       "#{ctx.app_dir}/#{s.artifact}",
          exec_start:   extract_directive(ctx.rendered[s.artifact], 'ExecStart'),
          restart:      "systemctl restart #{s.unit}",
          logs:         "journalctl -u #{s.unit} -n 200 -f"
        }
      end
    end

    # Lifecycle hook presence. Reflects what was on the local repo at
    # deploy time - local_* hooks run on your machine, remote_* ride along
    # with the rsync and run on the server.
    def hooks_section
      {
        local_before:  File.exist?(Commands::LOCAL_BEFORE_HOOK)  ? Commands::LOCAL_BEFORE_HOOK  : nil,
        remote_before: File.exist?(Commands::REMOTE_BEFORE_HOOK) ? Commands::REMOTE_BEFORE_HOOK : nil,
        remote_after:  File.exist?(Commands::REMOTE_AFTER_HOOK)  ? Commands::REMOTE_AFTER_HOOK  : nil,
        local_after:   File.exist?(Commands::LOCAL_AFTER_HOOK)   ? Commands::LOCAL_AFTER_HOOK   : nil
      }
    end

    # Non-secret env values; secret keys (see SENSITIVE_KEY_PATTERNS) keep
    # the key but the value is replaced with '<redacted>' so the LLM still
    # sees the variable exists.
    def env_section(env)
      env.each_with_object({}) do |(k, v), h|
        h[k] = (sensitive?(k) || sensitive_value?(v)) ? '<redacted>' : v
      end
    end

    def sensitive?(key)
      up = key.to_s.upcase
      SENSITIVE_KEY_PATTERNS.any? { |pat| up.include?(pat) }
    end

    def sensitive_value?(value)
      value.to_s.match?(CREDENTIAL_URL)
    end

    def git_info(branch)
      {
        branch:         branch,
        commit:         capture('git rev-parse HEAD'),
        commit_short:   capture('git rev-parse --short HEAD'),
        commit_subject: capture('git log -1 --pretty=%s'),
        author:         capture("git log -1 --pretty='%an <%ae>'"),
        committed_at:   capture('git log -1 --pretty=%cI')
      }
    end

    # Pull a single `Key=value` line out of a rendered systemd unit. Returns
    # nil when the directive isn't present, so the LLM can tell skip vs blank.
    def extract_directive(unit_text, key)
      return nil unless unit_text
      line = unit_text.lines.find { |l| l =~ /\A#{Regexp.escape(key)}=/ }
      line&.chomp&.sub(/\A#{Regexp.escape(key)}=/, '')
    end

    def triggered_by
      user = ENV['USER'] || ENV['LOGNAME'] || 'unknown'
      host = (Socket.gethostname rescue 'unknown')
      "#{user}@#{host}"
    end

    def capture(cmd)
      out = `#{cmd} 2>/dev/null`.strip
      out.empty? ? nil : out
    end

    # YAML.dump prefers string keys for portability + readability.
    def stringify(obj)
      case obj
      when Hash  then obj.each_with_object({}) { |(k, v), h| h[k.to_s] = stringify(v) }
      when Array then obj.map { |v| stringify(v) }
      else obj
      end
    end
  end
end
