require 'yaml'
require 'socket'
require 'time'

module LuxDeploy
  # Snapshot of what is wired up on the host for one app after a successful
  # deploy. Written to <app_dir>/lux-deploy.yaml mode 0644. Safe to read by
  # humans, LLMs, monitoring scripts - never contains secrets.
  module Manifest
    module_function

    FILENAME ||= 'lux-deploy.yaml'

    # Keys whose values are stripped from the env section. Matched on the
    # uppercased key name, substring (so SECRET, JWT_SECRET, DB_URL,
    # DATABASE_URL, MY_API_TOKEN, AWS_ACCESS_KEY_ID all redact).
    SENSITIVE_KEY_PATTERNS ||= %w[SECRET PASSWORD TOKEN KEY DB_URL DATABASE_URL CREDENTIAL].freeze

    # Returns the YAML body ready to upload (with a header comment).
    def render(ctx)
      header = <<~TXT
        # Generated by lux-deploy #{LuxDeploy::VERSION} on every successful deploy.
        # Snapshot of what is currently wired up on this host for this app.
        # Safe to read; do not edit (next deploy overwrites).
      TXT
      header + YAML.dump(stringify(build(ctx)))
    end

    def build(ctx)
      web_unit = "#{ctx.config.service_prefix}-#{ctx.app}"
      job_unit = (ctx.config.job_service_prefix && ctx.job_template?) \
                   ? "#{ctx.config.job_service_prefix}-#{ctx.app}" \
                   : nil

      env = Template.parse_env(ctx.rendered['.env'])
      domains = env[:DOMAIN].to_s.split(',').map(&:strip).reject(&:empty?)
      exec_start = extract_directive(ctx.rendered['systemd.service'], 'ExecStart')

      {
        deployed_at:  Time.now.utc.iso8601,
        app:          ctx.app,
        domain:       ctx.domain,
        domains:      domains,
        url:          "https://#{ctx.domain}",
        git:          git_info(ctx.branch),
        deploy: {
          triggered_by: triggered_by,
          host:         ctx.host,
          service_user: ctx.config.service_user,
          app_dir:      ctx.app_dir,
          port:         ctx.port,
          ruby:         ctx.ruby_path
        },
        paths: {
          release:     "#{ctx.app_dir}/release",
          old_release: "#{ctx.app_dir}/old-release",
          shared:      "#{ctx.app_dir}/shared",
          tmp:         "#{ctx.app_dir}/shared/tmp",
          log:         "#{ctx.app_dir}/shared/log",
          env_file:    "#{ctx.app_dir}/.env",
          manifest:    "#{ctx.app_dir}/#{FILENAME}"
        },
        services: services_section(ctx, web_unit, job_unit, exec_start),
        caddy: {
          site_link: "#{CADDY_SITES}/#{ctx.app}.caddy",
          source:    "#{ctx.app_dir}/caddy.config",
          reload:    'systemctl reload caddy'
        },
        hooks:     hooks_section,
        env:       env_section(env),
        artifacts: ctx.rendered.keys.sort,
        engine: {
          lux_deploy_version: LuxDeploy::VERSION,
          service_prefix:     ctx.config.service_prefix,
          remote_base:        ctx.config.remote_base
        }
      }
    end

    def services_section(ctx, web_unit, job_unit, exec_start)
      out = {
        web: {
          unit:         "#{web_unit}.service",
          systemd_link: "#{SYSTEMD_DIR}/#{web_unit}.service",
          source:       "#{ctx.app_dir}/systemd.service",
          exec_start:   exec_start,
          restart:      "systemctl restart #{web_unit}",
          logs:         "journalctl -u #{web_unit} -n 200 -f"
        }
      }
      if job_unit
        job_exec = extract_directive(ctx.rendered['systemd.job.service'], 'ExecStart')
        out[:job] = {
          unit:         "#{job_unit}.service",
          systemd_link: "#{SYSTEMD_DIR}/#{job_unit}.service",
          source:       "#{ctx.app_dir}/systemd.job.service",
          exec_start:   job_exec,
          restart:      "systemctl restart #{job_unit}",
          logs:         "journalctl -u #{job_unit} -n 200 -f"
        }
      end
      out
    end

    # Lifecycle hook presence. Reflects what was on the local repo at
    # deploy time - before_local.sh runs locally so it never lands on the
    # server, after_server.sh rides along with the rsync.
    def hooks_section
      {
        before_local: File.exist?(Commands::BEFORE_LOCAL_HOOK) ? Commands::BEFORE_LOCAL_HOOK : nil,
        after_server: File.exist?(Commands::AFTER_SERVER_HOOK) ? Commands::AFTER_SERVER_HOOK : nil
      }
    end

    # Non-secret env values; secret keys (see SENSITIVE_KEY_PATTERNS) keep
    # the key but the value is replaced with '<redacted>' so the LLM still
    # sees the variable exists.
    def env_section(env)
      env.each_with_object({}) do |(k, v), h|
        h[k] = sensitive?(k) ? '<redacted>' : v
      end
    end

    def sensitive?(key)
      up = key.to_s.upcase
      SENSITIVE_KEY_PATTERNS.any? { |pat| up.include?(pat) }
    end

    def git_info(branch)
      {
        branch:         branch,
        commit:         capture('git rev-parse HEAD'),
        commit_short:   capture('git rev-parse --short HEAD'),
        commit_subject: capture('git log -1 --pretty=%s'),
        author:         capture("git log -1 --pretty='%an <%ae>'"),
        committed_at:   capture('git log -1 --pretty=%cI')
      }
    end

    # Pull a single `Key=value` line out of a rendered systemd unit. Returns
    # nil when the directive isn't present, so the LLM can tell skip vs blank.
    def extract_directive(unit_text, key)
      return nil unless unit_text
      line = unit_text.lines.find { |l| l =~ /\A#{Regexp.escape(key)}=/ }
      line&.chomp&.sub(/\A#{Regexp.escape(key)}=/, '')
    end

    def triggered_by
      user = ENV['USER'] || ENV['LOGNAME'] || 'unknown'
      host = (Socket.gethostname rescue 'unknown')
      "#{user}@#{host}"
    end

    def capture(cmd)
      out = `#{cmd} 2>/dev/null`.strip
      out.empty? ? nil : out
    end

    # YAML.dump prefers string keys for portability + readability.
    def stringify(obj)
      case obj
      when Hash  then obj.each_with_object({}) { |(k, v), h| h[k.to_s] = stringify(v) }
      when Array then obj.map { |v| stringify(v) }
      else obj
      end
    end
  end
end
